version: '3'
services:
  llm_chat:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${PWD}/model/Wizard-Vicuna-7B-Uncensored.ggmlv3.q4_K_S.bin:/app/llm-model.bin
    environment:
      # Set the path to the llm as an environment variable
      MODEL_PATH: /app/llm-model.bin
    ports:
      - "8080:8080"
